server.port: 8888

spring:
  application.name: gateway
  config.zookeeper.connect-string: "localhost:2181"
  zipkin.base-url: "http://localhost:9411"
  sleuth.sampler.probability: 1.0
  cloud:
    gateway:
      routes:
        - id: menu-route
          uri: lb://binarytea
          predicates:
            - Path=/menu/**
        - id: order-route
          uri: lb://binarytea
          predicates:
            - Path=/order/**
        - id: token-route
          uri: http://localhost:8080
          predicates:
            - Path=/token

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: "*"
